# DATA LOAD

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import warnings
import seaborn as sns

warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
travel_22 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/2022년_국민여행조사_원자료_국내여행/2022년_1인필터링_관광.csv')
travel_23 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/2023년_국민여행조사_원자료_국내여행/travel_alone_2023.csv')

In [ ]:
travel_22.head()

,ID,SA1_1,SA1_2,SA1_3,SA1_4,SA1_5,MON_EXP_1,MON_EXP_2,MON_EXP_3,MON_EXP_4,...,A10A_5,A10A_6,A10A_7,A10A_8,A10A_9,A10A_10,A10A_11,A10A_12,A11,A12
0,1104055115A_302765,1,0,0,0,0,1,2,2,2,...,9,9,9,9,9,9,3,4,5,3
1,11060910451_379300,1,0,0,0,0,1,2,2,2,...,4,9,5,4,4,9,9,4,4,4
2,11070620491_505417,1,0,0,0,0,1,2,2,2,...,4,4,5,5,4,9,5,5,4,4
3,11080760641_505493,1,0,0,0,0,1,2,2,2,...,5,4,5,4,4,4,5,4,4,4
4,11090711631_505605,1,0,0,0,0,1,2,2,2,...,4,4,5,4,5,9,3,5,4,5

In [ ]:
travel_23.head()

,ID,SA1_1,SA1_2,SA1_3,SA1_4,SA1_5,SA1_6,MON_EXP_1,MON_EXP_2,MON_EXP_3,...,국내_A_기타전체여행_휴일,국내_A_기타전체여행_명절연휴,국내_A_기타숙박여행_평일,국내_A_기타숙박여행_주말,국내_A_기타숙박여행_휴일,국내_A_기타숙박여행_명절연휴,국내_A_기타당일여행_평일,국내_A_기타당일여행_주말,국내_A_기타당일여행_휴일,국내_A_기타당일여행_명절연휴
0,11010560931_124821,1,0,0,0,0,0,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11010560931_124833,1,0,0,0,0,0,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11010560931_124841,1,0,0,0,0,0,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11010560931_124849,1,0,0,0,0,0,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11010560931_124853,1,0,0,0,0,0,1,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

###필요한 X 칼럼, Y칼럼 정리

### 혼자 여행한 case에 대해서 wide format을 long format으로 변경후 진행

22년 데이터

In [ ]:
phases = [1, 2, 3, 4, 5, 6]
days = list(range(1, 18))

dfs = []

for i in phases:
    for j in days:
        col_name = f'D_TRA{i}_{j}_SPOT'
        if col_name in travel_22.columns:
            df_temp = travel_22[['ID']].copy()
            df_temp['차수'] = i
            df_temp['여행 인원'] = travel_22.get(f'D_TRA{i}_NUM')
            df_temp['지출 비용'] = travel_22.get(f'D_TRA{i}_COST')
            df_temp['방문 지역'] = travel_22.get(col_name)
            df_temp['여행 일수'] = travel_22.get(f'D_TRA{i}_S_Day')

            df_temp['철도비'] = travel_22.get('A9F_1')
            df_temp['도로비'] = travel_22.get('A9F_4')
            df_temp['식음료비'] = travel_22.get('A9E')
            df_temp['음식점비'] = travel_22.get('A9D')
            df_temp['쇼핑비'] = travel_22.get('A9H')
            df_temp['숙박비'] = travel_22.get('A9C')
            df_temp['교통비'] = travel_22.get('A9F')
            df_temp['여행 활동비'] = travel_22.get('A9G')
            dfs.append(df_temp)

long_df = pd.concat(dfs, ignore_index=True)
long_df = long_df.dropna(subset=['방문 지역'])

long_df['여행 인원'] = pd.to_numeric(long_df['여행 인원'], errors='coerce')
long_df['지출 비용'] = pd.to_numeric(long_df['지출 비용'], errors='coerce')
long_df['방문 지역'] = pd.to_numeric(long_df['방문 지역'], errors='coerce')
long_df['여행 일수'] = pd.to_numeric(long_df['여행 일수'], errors='coerce')
long_df['철도비'] = pd.to_numeric(long_df['철도비'], errors='coerce')
long_df['도로비'] = pd.to_numeric(long_df['도로비'], errors='coerce')
long_df['식음료비'] = pd.to_numeric(long_df['식음료비'], errors='coerce')
long_df['음식점비'] = pd.to_numeric(long_df['음식점비'], errors='coerce')
long_df['쇼핑비'] = pd.to_numeric(long_df['쇼핑비'], errors='coerce')
long_df['숙박비'] = pd.to_numeric(long_df['숙박비'], errors='coerce')
long_df['교통비'] = pd.to_numeric(long_df['교통비'], errors='coerce')


alone22_df = long_df[long_df['여행 인원'] == 1]

23년 데이터

In [ ]:
phases = [1, 2, 3, 4, 5, 6]
days = list(range(1, 18))

dfs = []

for i in phases:
    for j in days:
        col_name = f'D_TRA{i}_{j}_SPOT'
        if col_name in travel_23.columns:
            df_temp = travel_23[['ID']].copy()
            df_temp['차수'] = i
            df_temp['여행 인원'] = travel_23.get(f'D_TRA{i}_NUM')
            df_temp['지출 비용'] = travel_23.get(f'D_TRA{i}_COST')
            df_temp['방문 지역'] = travel_23.get(col_name)
            df_temp['여행 일수'] = travel_23.get(f'D_TRA{i}_S_Day')

            df_temp['철도비'] = travel_23.get('A9F_1')
            df_temp['도로비'] = travel_23.get('A9F_4')
            df_temp['식음료비'] = travel_23.get('A9E')
            df_temp['음식점비'] = travel_23.get('A9D')
            df_temp['쇼핑비'] = travel_23.get('A9H')
            df_temp['숙박비'] = travel_23.get('A9C')
            df_temp['교통비'] = travel_23.get('A9F')
            df_temp['여행 활동비'] = travel_23.get('A9G')

            dfs.append(df_temp)

long_df = pd.concat(dfs, ignore_index=True)
long_df = long_df.dropna(subset=['방문 지역'])

long_df['여행 인원'] = pd.to_numeric(long_df['여행 인원'], errors='coerce')
long_df['지출 비용'] = pd.to_numeric(long_df['지출 비용'], errors='coerce')
long_df['방문 지역'] = pd.to_numeric(long_df['방문 지역'], errors='coerce')
long_df['여행 일수'] = pd.to_numeric(long_df['여행 일수'], errors='coerce')
long_df['철도비'] = pd.to_numeric(long_df['철도비'], errors='coerce')
long_df['도로비'] = pd.to_numeric(long_df['도로비'], errors='coerce')
long_df['식음료비'] = pd.to_numeric(long_df['식음료비'], errors='coerce')
long_df['음식점비'] = pd.to_numeric(long_df['음식점비'], errors='coerce')
long_df['쇼핑비'] = pd.to_numeric(long_df['쇼핑비'], errors='coerce')
long_df['숙박비'] = pd.to_numeric(long_df['숙박비'], errors='coerce')
long_df['교통비'] = pd.to_numeric(long_df['교통비'], errors='coerce')

alone23_df = long_df[long_df['여행 인원'] == 1]

In [ ]:
grouped_22_23_df = pd.concat([alone22_df, alone23_df])

grouped_22_23_df = grouped_22_23_df.groupby('방문 지역').agg({
    '지출 비용': 'mean',
    # '지출 비용': 'sum',
    '철도비': 'mean',
    '도로비': 'mean',
    '식음료비': 'mean',
    '음식점비': 'mean',
    '쇼핑비': 'mean',
    '여행 일수': 'mean',
    '숙박비': 'mean',
    '교통비': 'mean',
    '여행 활동비': 'mean'
}).reset_index()

grouped_22_23_df['방문 지역'] = grouped_22_23_df['방문 지역'].astype(int)

print(grouped_22_23_df.head())

   방문 지역          지출 비용           철도비           도로비          식음료비  \
0  11010  188737.500000  16338.157895  12750.000000  15074.626866
1  11020  214134.139535  20353.488372  13018.604651  16385.714286
2  11030  211063.360000  27440.000000   5608.000000   5456.521739
3  11040   86000.000000   5375.000000  12750.000000  31200.000000
4  11050  157083.333333   6500.000000   8000.000000  13200.000000

           음식점비           쇼핑비     여행 일수           숙박비           교통비  \
0  58697.268657  29552.238806  0.567164  19417.910448  46732.894737
1  55505.771429  66565.714286  0.257143   9142.857143  58441.883721
2  75782.608696  11469.565217  0.739130  23086.956522  64528.040000
3  79000.000000      0.000000  0.200000      0.000000  33125.000000
4  75400.000000   5000.000000  0.400000  14000.000000  60333.333333

        여행 활동비
0  8432.835821
1  4571.428571
2  9434.782609
3       3000.0
4       4400.0

In [ ]:
# # 1. 먼저 두 연도 별 지출 비용 합계를 각각 구함
# alone22_cost = alone22_df[['방문 지역', '지출 비용']].copy()
# alone23_cost = alone23_df[['방문 지역', '지출 비용']].copy()

# alone22_cost = alone22_cost.groupby('방문 지역')['지출 비용'].sum().reset_index()
# alone23_cost = alone23_cost.groupby('방문 지역')['지출 비용'].sum().reset_index()

# # 2. 22, 23년 지출 비용 평균 계산
# cost_df = pd.merge(alone22_cost, alone23_cost, on='방문 지역', how='outer', suffixes=('_22', '_23'))
# cost_df = cost_df.fillna(0)  # 둘 중 하나 없는 경우 0으로 처리
# cost_df['지출 비용'] = (cost_df['지출 비용_22'] + cost_df['지출 비용_23']) / 2
# cost_df = cost_df[['방문 지역', '지출 비용']]

# # 3. 나머지 비용 평균은 기존 grouped_22_23_df에서 사용
# other_cols = ['철도비', '도로비', '식음료비', '음식점비', '쇼핑비', '여행 일수', '숙박비', '교통비', '여행 활동비']
# grouped_22_23_df = pd.concat([alone22_df, alone23_df])

# others_df = grouped_22_23_df.groupby('방문 지역')[other_cols].mean().reset_index()

# # 4. 지출 비용 평균과 나머지 평균을 병합
# grouped_22_23_df = pd.merge(cost_df, others_df, on='방문 지역', how='inner')
# grouped_22_23_df['방문 지역'] = grouped_22_23_df['방문 지역'].astype(int)

# print(grouped_22_23_df.head())

In [ ]:
grouped_22_23_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 224 entries, 0 to 223
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   방문 지역   224 non-null    int64
 1   지출 비용   224 non-null    float64
 2   철도비     224 non-null    float64
 3   도로비     224 non-null    float64
 4   식음료비    222 non-null    float64
 5   음식점비    222 non-null    float64
 6   쇼핑비     222 non-null    float64
 7   여행 일수   222 non-null    float64
 8   숙박비     222 non-null    float64
 9   교통비     224 non-null    float64
 10  여행 활동비  222 non-null    object
dtypes: float64(9), int64(1), object(1)
memory usage: 19.4+ KB

In [ ]:
car_dep_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/자가용 의존도/car dependency_all.csv')

In [ ]:
car_dep_df.head()

   region_code  car_count  non_car_count  total_count  car_ratio
0        11010         18             83          101   0.178218
1        11020         19             39           58   0.327586
2        11030         11             20           31   0.354839
3        11040          5             13           18   0.277778
4        11050          2             18           20   0.100000

In [ ]:
car_merge_df = car_dep_df[['region_code', 'car_ratio']].copy()

car_merge_df.rename(columns={'region_code': '방문 지역', 'car_ratio': '자가용 의존도'}, inplace=True)

# 병합: 방문 지역 기준으로 인프라 지수 붙이기
merged_df = grouped_22_23_df.merge(car_merge_df, on='방문 지역', how='left')

# 결과 확인
print(merged_df.head())

   방문 지역          지출 비용           철도비           도로비          식음료비  \
0  11010  188737.500000  16338.157895  12750.000000  15074.626866
1  11020  214134.139535  20353.488372  13018.604651  16385.714286
2  11030  211063.360000  27440.000000   5608.000000   5456.521739
3  11040   86000.000000   5375.000000  12750.000000  31200.000000
4  11050  157083.333333   6500.000000   8000.000000  13200.000000

           음식점비           쇼핑비     여행 일수           숙박비           교통비  \
0  58697.268657  29552.238806  0.567164  19417.910448  46732.894737
1  55505.771429  66565.714286  0.257143   9142.857143  58441.883721
2  75782.608696  11469.565217  0.739130  23086.956522  64528.040000
3  79000.000000      0.000000  0.200000      0.000000  33125.000000
4  75400.000000   5000.000000  0.400000  14000.000000  60333.333333

        여행 활동비   자가용 의존도
0  8432.835821  0.178218
1  4571.428571  0.327586
2  9434.782609  0.354839
3       3000.0  0.277778
4       4400.0  0.100000

In [ ]:
# grouped_22_23_df.to_csv('train.csv', index=False)
# from google.colab import files
# files.download('train.csv')

In [ ]:
# merged_df.to_csv('train.csv', index=False)
# from google.colab import files
# files.download('train.csv')

In [ ]:
infra_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/교통인프라지수_최종(정원)/교통인프라지수_최종 (3).csv')

In [ ]:
infra_df.head()

   Unnamed: 0  시군구코드  교통인프라지수_norm
0          74  31020      3.429257
1          22  11230      3.299027
2          21  11220      2.971521
3          23  11240      2.737020
4          20  11210      2.529984

In [ ]:
infra_merge_df = infra_df[['시군구코드', '교통인프라지수_norm']].copy()

infra_merge_df.rename(columns={'시군구코드': '방문 지역', '교통인프라지수_norm': '교통인프라지수'}, inplace=True)

# 병합: 방문 지역 기준으로 인프라 지수 붙이기
merge_df = merged_df.merge(infra_merge_df, on='방문 지역', how='left')

# 결과 확인
print(merge_df.head())

   방문 지역          지출 비용           철도비           도로비          식음료비  \
0  11010  188737.500000  16338.157895  12750.000000  15074.626866
1  11020  214134.139535  20353.488372  13018.604651  16385.714286
2  11030  211063.360000  27440.000000   5608.000000   5456.521739
3  11040   86000.000000   5375.000000  12750.000000  31200.000000
4  11050  157083.333333   6500.000000   8000.000000  13200.000000

           음식점비           쇼핑비     여행 일수           숙박비           교통비  \
0  58697.268657  29552.238806  0.567164  19417.910448  46732.894737
1  55505.771429  66565.714286  0.257143   9142.857143  58441.883721
2  75782.608696  11469.565217  0.739130  23086.956522  64528.040000
3  79000.000000      0.000000  0.200000      0.000000  33125.000000
4  75400.000000   5000.000000  0.400000  14000.000000  60333.333333

        여행 활동비   자가용 의존도   교통인프라지수
0  8432.835821  0.178218  1.423597
1  4571.428571  0.327586  1.696777
2  9434.782609  0.354839  1.328858
3       3000.0  0.277778  0.777908
4       4400.0  0.100000  1.065124

In [ ]:
# grouped_22_23_df.to_csv('train.csv', index=False)
# from google.colab import files
# files.download('train.csv')

In [ ]:
merge_df.to_csv('train.csv', index=False)
from google.colab import files
files.download('train.csv')